### ISSUE TITLE
Alert message is not showing

### ISSUE THREAD

**Issue by aaqibqadeer** [MathijsBlok/ngx-alerts#10]
I have added ngx tag in my template but the alert message is not showing.
```
<ngx-alerts></ngx-alerts>
<form>
..........
</form>
```

I think it's maybe because of the complex structure of my project. I have multiple modules.

First I added these imports in my main app module.
```
// app.module.ts
imports: [
    BrowserAnimationsModule,
    BrowserModule,
    AlertModule.forRoot({ maxMessages: 5, timeout: 5000, position: 'right' })
  ],
```
After it didn't work, I also added the Alert Module import in the local module file

```
// vendor.module.ts
@NgModule({
  imports: [
    AlertModule.forRoot({ maxMessages: 5, timeout: 5000, position: 'right' })
  ],
```

Please guide me, how can I resolve this issue? Thanks

**Comment by MathijsBlok** [comment]
I think your app module should be

imports: [
    BrowserAnimationsModule,
    BrowserModule,
    AlertModule.forRoot({ maxMessages: 5, timeout: 5000, position: 'right' })
  ],

And your vendor module

imports: [
    AlertModule
  ],

**Comment by aaqibqadeer** [comment]
It's still not working. It's showing this error
```
ERROR in node_modules/ngx-alerts/lib/component/alert.component.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context. 
node_modules/ngx-alerts/lib/service/alert.service.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
```

Note: I also encountered this error before, but I don't know what I did, because it disappeared.

**Comment by MathijsBlok** [comment]
What angular version are you using?

**Comment by aaqibqadeer** [comment]
angular 7.0.7

**Comment by MathijsBlok** [comment]
can you try to install version 3.4.5 of the library? (npm i --save ngx-alerts@3.4.5)

**Comment by aaqibqadeer** [comment]
Error is resolved after installing version 3.4.5. But alert is still not showing

**Comment by aaqibqadeer** [comment]
It is working. 
Before using this library, I had simple alert messages and redirection links after that. It was working fine. So when I replaced the alert messages with this service, the message was not being displayed. I just removed the redirection link and it is working now.

**Comment by aaqibqadeer** [comment]
Thank you so much. the issue is resolved.
