### ISSUE TITLE
Position bottom support

### ISSUE THREAD

**Issue by iravitejakumar** [MathijsBlok/ngx-alerts#13]
After refering to documentation, I came to know that this library is supporting only top right and top left position.

Is there any way to poistion alert to bottom of the page ?

It would to great, If it can be extended to position alert to bottom. 

Thanks in Advance :)

**Comment by MathijsBlok** [comment]
Added this in version 10.1.0, there is now a positionX (which can be left of right) and a positionY (which can be left or right)

**Comment by MathijsBlok** [comment]
Fixed in 10.1.1, there is now a positionX which can be left or right and a positionY which can be top or bottom

**Comment by iravitejakumar** [comment]
> Fixed in 10.1.1, there is now a positionX which can be left or right and a positionY which can be top or bottom

Awesome @MathijsBlok . I will use 10.1.1 version. Thanks for the update and quick response.

**Comment by MathijsBlok** [comment]
You're welcome!
