### ISSUE TITLE
Allow better/some control over where the alert(s) is(are) placed

### ISSUE THREAD

**Issue by jbisotti** [MathijsBlok/ngx-alerts#2]
Regardless of where I put `<ngx-alerts></ngx-alerts>`, the alert always appears in the same location. I use Bootstrap 4, with "container". Horizontally speaking the alert is partly inside the container area and partly outside of it, in the otherwise empty side gutters. Vertically speaking, it is always over my navbar; I think it would look better at the top of the page "body".

That said, thanks for this component; it's save me some time and effort.

**Comment by mohamedelmancy** [comment]
+1

**Comment by MathijsBlok** [comment]
it has an absolute position. So it will allways be in the top right corner.

If you include some global css to overwrite the position of .app-alerts you can change it. But the animations will probably go in the wrong direction then.

**Comment by MathijsBlok** [comment]
I'll maybe work on some parameters to make it variable this weekend.
