### ISSUE TITLE
Import warning with Angular 9

### ISSUE THREAD

**Issue by btxtiger** [MathijsBlok/ngx-alerts#7]
I'm getting this import warning with Angular 9:

`Warning: Entry point 'ngx-alerts' contains deep imports into '/Users/*****/*****/*****/node_modules/rxjs/internal/operators'. This is probably not a problem, but may cause the compilation of entry points to be out of order.`

The correct import path should be
`import { debounceTime, map, startWith, tap } from 'rxjs/operators';`

**Comment by MathijsBlok** [comment]
Thanks, fixed it in version 9.0.2
